import matplotlib
matplotlib.use('Agg')

from flask import Flask, render_template, request, send_file

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.linear_model import LinearRegression
import numpy as np
from fpdf import FPDF

from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split



app = Flask(__name__)

def generate_pdf(report_text):

    pdf = FPDF()

    pdf.add_page()

    pdf.set_font("Arial", size=12)

    lines = report_text.split("\n")

    for line in lines:
        pdf.multi_cell(0, 10, line)

    pdf_file = "reports/stock_report.pdf"

    pdf.output(pdf_file)

    return pdf_file




@app.route("/", methods=["GET", "POST"])
def index():

    table = None
    graph_generated = False
    predicted_price = None
    recommendation = None
    current_price = None
    report = None
    mae = None

    if request.method == "POST":

        stock_symbol = request.form["stock"].upper()

        if ".NS" not in stock_symbol:
            stock_symbol += ".NS"

        # Download stock data
        stock_data = yf.download(stock_symbol, period="3mo")

        # Reset index
        stock_data.reset_index(inplace=True)

        # Convert table to HTML
        table = stock_data.to_html(classes='table table-striped')

        # Machine Learning Prediction

        stock_data['Prediction_Day'] = np.arange(len(stock_data))

        X = stock_data[['Prediction_Day']]

        y = stock_data['Close']

        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=0.2,
            random_state=42
        )

        model = LinearRegression()

        # model.fit(X, y)

        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)

        mae = mean_absolute_error(y_test, y_pred)

        mae = round(float(mae), 2)


        next_day = [[len(stock_data)]]

        predicted_price = model.predict(next_day)

        predicted_price = round(float(predicted_price[0]), 2)

        current_price = round(float(stock_data['Close'].iloc[-1]), 2)

        price_difference = predicted_price - current_price

        if price_difference > 20:
            recommendation = "BUY"

        elif price_difference < -20:
            recommendation = "SELL"

        else:
            recommendation = "HOLD"


        # Automated Report Generation

        if recommendation == "BUY":
            trend_analysis = "The stock shows positive momentum based on historical data."
        elif recommendation == "SELL":
            trend_analysis = "The stock shows negative momentum based on historical data."
        else:
            trend_analysis = "The stock is currently moving in a stable range."

        # report = f"""
        # AI STOCK ANALYSIS REPORT

        # Stock Symbol: {stock_symbol}

        # Current Price: Rs. {current_price}

        # Predicted Price: Rs. {predicted_price}

        # Recommendation: {recommendation}

        # Trend Analysis:
        # {trend_analysis}

        # AI Observation:
        # The recommendation is generated automatically using machine learning prediction and trend comparison.

        # Generated By:
        # AI-Powered Automated Stock Report Generation System
        # """


        report = f"""
        EXECUTIVE STOCK ANALYSIS REPORT

        Company Symbol: {stock_symbol}

        Current Market Price: Rs. {current_price}

        AI Predicted Price: Rs. {predicted_price}

        Investment Recommendation: {recommendation}

        =================================
        MARKET TREND ANALYSIS
        {trend_analysis}

       
        Business Insight:
        The machine learning model predicts future stock movement by analyzing historical market behavior. Based on the prediction and trend comparison, the system has generated the above investment recommendation.

    
        Conclusion:
        Investors may use this analysis as an educational decision-support tool. Actual investment decisions should consider additional market and financial factors.

        Generated Automatically By:
        AI-Powered Automated Stock Report Generation System
        """

        generate_pdf(report)


        # Create stock graph
        plt.figure(figsize=(10,5))

        plt.plot(stock_data.index, stock_data['Close'])

        plt.title(f"{stock_symbol} Closing Price Trend")

        plt.xlabel("Date")

        plt.ylabel("Closing Price")

        plt.xticks(rotation=45)

        plt.tight_layout()

        # Save graph image
        graph_path = os.path.join("static", "stock_graph.png")

        plt.savefig(graph_path)

        plt.close()

        graph_generated = True



    return render_template(
      "index.html",
      tables=table,
      graph_generated=graph_generated,
      predicted_price=predicted_price,
      recommendation=recommendation,
      current_price=current_price,
      report=report,
      mae=mae
    )



@app.route("/download_pdf")
def download_pdf():

    pdf_path = "reports/stock_report.pdf"

    return send_file(
        pdf_path,
        as_attachment=True
    )



if __name__ == "__main__":
    app.run(debug=True)